name = "litegraph_to_ada"
description = "An Ada library create and use graph on LiteGraph js"
version = "0.1.0-dev"
licenses = "MIT"
website = "https://github.com/Fabien-Chouteau/litegraph_to_ada"
tags = ["litegraph", "graph", "gui"]

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]
